import type { DatasetId } from "./catalog";

export type DatasetGovernance = {
  cadence: "stream" | "poll" | "request" | "cron" | "derived" | "control";
  entrypoint: "api" | "internal" | "client";
  recoveryOwner: "automatic" | "tws_recovery" | "reload" | "retry" | "none";
};

/** Required onboarding metadata; adding a DatasetId must update this record. */
export const DATASET_GOVERNANCE = {
  chart_candles: { cadence: "poll", entrypoint: "api", recoveryOwner: "reload" },
  watchlist_quotes: { cadence: "stream", entrypoint: "api", recoveryOwner: "automatic" },
  instrument_search: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  fundamentals_display: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  options_expirations: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  options_chain: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  screener_descriptive: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  screener_technical: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  screener_universe_daily: { cadence: "cron", entrypoint: "internal", recoveryOwner: "automatic" },
  screener_movers: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  events_market: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  news_symbol: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  macro_series: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  sec_filings_direct: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  fmp_profile: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  fmp_estimates: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  fmp_financials: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  fmp_executives: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  fmp_sec_filings_search: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  market_context: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  derived_metrics: { cadence: "derived", entrypoint: "internal", recoveryOwner: "none" },
  chart_indicators: { cadence: "derived", entrypoint: "client", recoveryOwner: "none" },
  account_summary: { cadence: "stream", entrypoint: "api", recoveryOwner: "tws_recovery" },
  positions: { cadence: "stream", entrypoint: "api", recoveryOwner: "tws_recovery" },
  orders: { cadence: "poll", entrypoint: "api", recoveryOwner: "tws_recovery" },
  executions_fills: { cadence: "poll", entrypoint: "api", recoveryOwner: "tws_recovery" },
  account_pnl: { cadence: "stream", entrypoint: "api", recoveryOwner: "tws_recovery" },
  pre_trade_quote: { cadence: "request", entrypoint: "api", recoveryOwner: "tws_recovery" },
  order_intents: { cadence: "request", entrypoint: "api", recoveryOwner: "none" },
  broker_ledger_ingest: { cadence: "cron", entrypoint: "api", recoveryOwner: "tws_recovery" },
  journal_trades: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  watchlist_library: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  screener_library: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  chart_workspaces: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  chart_templates: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  script_library: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  research_notes: { cadence: "request", entrypoint: "api", recoveryOwner: "retry" },
  account_snapshots: { cadence: "cron", entrypoint: "api", recoveryOwner: "retry" },
  pattern_library: { cadence: "request", entrypoint: "api", recoveryOwner: "none" },
  risk_settings: { cadence: "request", entrypoint: "client", recoveryOwner: "none" },
  market_data_warmup: { cadence: "control", entrypoint: "api", recoveryOwner: "automatic" },
  market_data_health: { cadence: "poll", entrypoint: "api", recoveryOwner: "automatic" },
  tws_recovery: { cadence: "control", entrypoint: "api", recoveryOwner: "tws_recovery" },
  tws_ibkr_probes: { cadence: "request", entrypoint: "api", recoveryOwner: "none" },
} as const satisfies Record<DatasetId, DatasetGovernance>;

export const DATA_ROUTE_REGISTRATIONS = {
  "candles/route.ts": ["chart_candles"],
  "quotes/route.ts": ["watchlist_quotes"],
  "search/route.ts": ["instrument_search"],
  "fundamentals/route.ts": ["fundamentals_display"],
  "options/expirations/route.ts": ["options_expirations"],
  "options/chain/route.ts": ["options_chain"],
  "screener/run/route.ts": ["screener_descriptive", "screener_technical"],
  "events/route.ts": ["events_market"],
  "news/route.ts": ["news_symbol"],
  "macro/series/route.ts": ["macro_series"],
  "sec/filings/route.ts": ["sec_filings_direct"],
  "market-data/context/route.ts": ["market_context"],
  "market-data/fmp/profile/route.ts": ["fmp_profile"],
  "market-data/fmp/estimates/route.ts": ["fmp_estimates"],
  "market-data/fmp/financials/route.ts": ["fmp_financials"],
  "market-data/fmp/executives/route.ts": ["fmp_executives"],
  "market-data/fmp/filings/route.ts": ["fmp_sec_filings_search"],
  "market-data/fmp/movers/route.ts": ["screener_movers"],
  "stream/candles/route.ts": ["chart_candles"],
  "stream/quotes/route.ts": ["watchlist_quotes"],
  "market-data/health/route.ts": ["market_data_health"],
  "market-data/warmup/route.ts": ["market_data_warmup"],
  "market-data/tws/recover/route.ts": ["tws_recovery"],
  "market-data/tws/recover/status/route.ts": ["tws_recovery"],
  "market-data/tws/status/route.ts": ["tws_ibkr_probes"],
  "market-data/tws/contracts/route.ts": ["tws_ibkr_probes"],
  "market-data/tws/quote/route.ts": ["tws_ibkr_probes"],
  "market-data/tws/candles/route.ts": ["tws_ibkr_probes"],
  "market-data/ibkr/status/route.ts": ["tws_ibkr_probes"],
  "market-data/ibkr/contracts/route.ts": ["tws_ibkr_probes"],
  "market-data/ibkr/quote/route.ts": ["tws_ibkr_probes"],
  "market-data/ibkr/candles/route.ts": ["tws_ibkr_probes"],
  "brokerage/stream/route.ts": ["account_summary", "positions", "account_pnl"],
  "brokerage/snapshot/route.ts": ["account_summary", "positions"],
  "brokerage/summary/route.ts": ["account_summary"],
  "brokerage/positions/route.ts": ["positions"],
  "brokerage/pnl/route.ts": ["account_pnl"],
  "brokerage/orders/route.ts": ["orders"],
  "brokerage/trades/route.ts": ["executions_fills"],
  "brokerage/status/route.ts": ["account_summary"],
  "brokerage/whatif/route.ts": ["pre_trade_quote"],
  "trading/accounts/route.ts": ["account_summary"],
  "trading/preview/route.ts": ["pre_trade_quote", "order_intents"],
  "trading/orders/route.ts": ["order_intents"],
  "trading/orders/[orderId]/route.ts": ["order_intents"],
  "cron/brokerage-ingest/route.ts": ["broker_ledger_ingest", "account_snapshots"],
  "me/brokerage-ingest/status/route.ts": ["broker_ledger_ingest"],
  "me/journal/import/route.ts": ["journal_trades"],
  "me/journal/fills/route.ts": ["journal_trades", "executions_fills"],
  "me/journal/trades/route.ts": ["journal_trades"],
  "me/journal/trades/[id]/route.ts": ["journal_trades"],
  "me/journal/trades/rebuild/route.ts": ["journal_trades"],
  "me/watchlist-library/route.ts": ["watchlist_library"],
  "me/screener-library/route.ts": ["screener_library"],
  "me/chart-workspaces/route.ts": ["chart_workspaces"],
  "me/chart-workspaces/[id]/route.ts": ["chart_workspaces"],
  "me/chart-workspaces/default/route.ts": ["chart_workspaces"],
  "me/chart-template-library/route.ts": ["chart_templates"],
  "me/scripts/route.ts": ["script_library"],
  "me/scripts/import/route.ts": ["script_library"],
  "me/scripts/[scriptId]/route.ts": ["script_library"],
  "me/scripts/[scriptId]/revisions/route.ts": ["script_library"],
  "me/scripts/[scriptId]/revisions/[revision]/route.ts": ["script_library"],
  "me/market-research-notes/route.ts": ["research_notes"],
  "me/market-research-notes/[id]/route.ts": ["research_notes"],
  "me/account-snapshots/route.ts": ["account_snapshots"],
} as const satisfies Record<string, readonly DatasetId[]>;

export const API_ROUTE_EXCLUSIONS = {
  "auth/dev-session/route.ts": "authentication control plane",
  "dev/local-errors/route.ts": "local diagnostics control plane",
  "ai/tools/route.ts": "AI tool discovery, not a dataset producer",
  "ai/tools/execute/route.ts": "AI registry adapter",
  "ai/session/execute/route.ts": "AI session control plane",
  "ai/session/heartbeat/route.ts": "AI session control plane",
  "ai/session/poll/route.ts": "AI session control plane",
  "ai/session/result/route.ts": "AI session control plane",
  "me/pattern-library/captures/route.ts": "user content excluded from data health",
  "me/pattern-library/records/route.ts": "user content excluded from data health",
  "me/pattern-library/records/[id]/route.ts": "user content excluded from data health",
  "me/pattern-library/taxonomy/route.ts": "user content excluded from data health",
  "pattern-library/captures/route.ts": "user content excluded from data health",
  "pattern-library/records/route.ts": "user content excluded from data health",
  "pattern-library/records/[id]/route.ts": "user content excluded from data health",
  "pattern-library/records/[id]/svg/route.ts": "user content excluded from data health",
  "pattern-library/taxonomy/route.ts": "user content excluded from data health",
  "day-profiles/route.ts": "user content excluded from data health",
} as const;
