ALTER TABLE alert_definitions
  ADD COLUMN IF NOT EXISTS drawing_id TEXT,
  ADD COLUMN IF NOT EXISTS drawing_kind TEXT,
  ADD COLUMN IF NOT EXISTS price_high DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tl_t0 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tl_v0 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tl_t1 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tl_v1 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tl_extend_left BOOLEAN,
  ADD COLUMN IF NOT EXISTS tl_extend_right BOOLEAN;

CREATE INDEX IF NOT EXISTS alert_definitions_drawing_id_idx
  ON alert_definitions (drawing_id)
  WHERE drawing_id IS NOT NULL;
